### ISSUE TITLE
Labels are not visible when margins are removed. 

### ISSUE THREAD

**Issue by zackarychapple** [jtraband/career-builder-d3#2]
When using `margin: {top: 0, right: 0, bottom: 0, left: 0},` on Horizontal Bar Charts with no x-axis the y-axis disappears. I assume the same issue occurs with the x-axis as well. 
![screen shot 2016-06-02 at 8 45 13 am](https://cloud.githubusercontent.com/assets/2133184/15745303/1dea5278-289f-11e6-8d2a-eebc9d0989fe.png)

**Comment by jtraband** [comment]
The margins are for axis labels and the title ( and axis legends if we add them) as well as ‘above’ and ‘below’ legends.  The margins are still ‘part’ of the overall width and height though,  meaning that the width and height of the chart represent the ‘full’  dimensions of your chart.  This is a d3 convention that I think works pretty well.  Does this make sense?

**Comment by jtraband** [comment]
The margins are where all ‘extra’ cruft appears.  With 0 margins none of the extra stuff ( titles, axis labels, etc) will appear.  Adding margins just causes the ‘chart’ area to shrink in relation so the overall size of the chart does not change and the margins must be large enough to accommodate whatever space the ‘extra’ stuff needs.

**Comment by zackarychapple** [comment]
How do we calculate the size needed for the 'extra' stuff

**Comment by jtraband** [comment]
It's doable but is not trivial and gets substantially harder as we add new options that provide more text in any of the margins.  i.e. as we put more than one thing in a a margin.  For example, right now the top margin may contain a title and legends ( possibly mulitple lines of legends) each of which itself can be of a different font size.  I'm not sure if the effort required to implement this is worth the cost. It also precludes or makes difficult some features such as angled tick titles on the xAxis. The alternative is trial and error by the dev, but honestly this is pretty easy and fixed margins work for the vast majority of cases.  But that said, it is doable, just difficult.

**Comment by zackarychapple** [comment]
Maybe we make the margin something that is passed in, that way we can do some calculation on the component to decide how big to make the margin? Not saying we should do this, just throwing out an idea.

**Comment by jtraband** [comment]
margin is passed in.  In 'options' for all of the chart types. ( except funnel).

**Comment by zackarychapple** [comment]
fair enough.
