### ISSUE TITLE
Axis bars are too thick

### ISSUE THREAD

**Issue by zackarychapple** [jtraband/career-builder-d3#4]
Currently the axis bars appear to be ~5 px thick. These should be thinner (1px) and be #555 in color. 

![screen shot 2016-06-02 at 9 15 22 am](https://cloud.githubusercontent.com/assets/2133184/15745987/951778e6-28a2-11e6-9ddf-937269c7bbf7.png)

**Comment by jtraband** [comment]
This should be provided by the styles.css file in the repo.  
![image](https://cloud.githubusercontent.com/assets/1766167/15756203/1001f718-28b5-11e6-947f-1d7dfbaf7f4a.png)

**Comment by zackarychapple** [comment]
Much better. I missed that file.
